### PR TITLE
fix(debugger): fix reset all state, remember(time travel)

### PR DESCRIPTION
**Pull request by yusufsafak**
connector.sendEvent needs port

By the way I don't have permission for this repo :(

### CODE REVIEW

**Review by henri-hulski — COMMENTED** [review]
I think @christianalfoni should review this as I don't know much about the internals.

**Review by christianalfoni — APPROVED** [review]
Great! Thanks! :)

**Comment by christianalfoni** [comment]
@reflog Could we try to pull this in and test deploy routine? could you bump me where to download when it is published? I will test this with a cerebral PR, where @yusufsafak has done an amazing refactor of devtools :)

**Comment by reflog** [comment]
Sure thing. I'm merging the code in and once it's done building, the executables will appear at: https://github.com/cerebral/cerebral-debugger/releases

**Comment by christianalfoni** [comment]
Btw, I will test on Thursday (national holiday in Norway tomorrow), stay tuned :)

**Pull request merged**
